// flow-typed signature: 7cf6a6bfc2e6b9844c74720672350f33
// flow-typed version: <<STUB>>/customize-cra-react-refresh_v^1.0.1/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'customize-cra-react-refresh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'customize-cra-react-refresh' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'customize-cra-react-refresh/index' {
  declare module.exports: $Exports<'customize-cra-react-refresh'>;
}
declare module 'customize-cra-react-refresh/index.js' {
  declare module.exports: $Exports<'customize-cra-react-refresh'>;
}
