// flow-typed signature: b3cf4771c1bbf5d1f7fba2f4f4469b25
// flow-typed version: <<STUB>>/material-ui-confirm_v^2.0.4/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-confirm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-confirm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-confirm/dist/material-ui-confirm.cjs' {
  declare module.exports: any;
}

declare module 'material-ui-confirm/dist/material-ui-confirm.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-confirm/dist/material-ui-confirm.cjs.js' {
  declare module.exports: $Exports<'material-ui-confirm/dist/material-ui-confirm.cjs'>;
}
declare module 'material-ui-confirm/dist/material-ui-confirm.esm.js' {
  declare module.exports: $Exports<'material-ui-confirm/dist/material-ui-confirm.esm'>;
}
