// flow-typed signature: 507fa7d2cc70971190435cd2b92eed9d
// flow-typed version: <<STUB>>/node-zip_v^1.1.1/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-zip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-zip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-zip/lib/nodezip-cli' {
  declare module.exports: any;
}

declare module 'node-zip/lib/nodezip' {
  declare module.exports: any;
}

declare module 'node-zip/test/nodezip_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-zip/lib/nodezip-cli.js' {
  declare module.exports: $Exports<'node-zip/lib/nodezip-cli'>;
}
declare module 'node-zip/lib/nodezip.js' {
  declare module.exports: $Exports<'node-zip/lib/nodezip'>;
}
declare module 'node-zip/test/nodezip_spec.js' {
  declare module.exports: $Exports<'node-zip/test/nodezip_spec'>;
}
